export const LEVELS = [
  'font-family: sans-serif;',
  'color: white;',
  'font-size: 20px;',
  'text-transform: uppercase;',
  'font-kerning: none;',
  'font-variant-caps: all-small-caps;',
  'font-weight: bold;',
  'font-style: italic;',
  'text-decoration: underline;',
  'letter-spacing: 1px;',
  'word-spacing: 5px;',
  'line-height: 1.5;',
  'text-indent: 20px;',
  'text-align: center;',
  'text-shadow: 1px 1px lightgray;',
  'overflow: hidden;\nwhite-space: nowrap;\ntext-overflow: ellipsis;',
  'direction: rtl;',
  'text-emphasis: triangle;',
  'writing-mode: vertical-lr;',
  'text-orientation: upright;',
];

export const LEVEL_DESCRIPTIONS = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '20',
  '21',
];
